{{- include "kubernetes-role-generator" (merge (dict "namespace" .Values.defaultNamespace "component" "timer") .) }}

{{- if not .Values.fissionOnAllNamespaces -}}
  {{- if gt (len .Values.additionalFissionNamespaces) 0 }}
  {{- range $namespace := $.Values.additionalFissionNamespaces }}
  {{ include "kubernetes-role-generator" (merge (dict "namespace" $namespace "component" "timer") $) }}
  {{- end }}
  {{- end }}
{{- end }}
