
{{- if .Values.azureStorageQueue.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-key
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  key: {{ required "An Azure storage access key is required." .Values.azureStorageQueue.key | b64enc | quote }}
{{- end }}
