version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit:  5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /cmd/builder
      - /cmd/fetcher
      - /cmd/fission-bundle
      - /cmd/preupgradechecks
      - /cmd/reporter
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    exclude-paths:
      - "test/*"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit:  5
    exclude-paths:
      - "test/*"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: helm
    directory: /charts/fission-all
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      helm-charts:
        patterns:
          - "*"
