version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit:  5
    groups:
      github-actions:
        patterns: 
          - "*"

  - package-ecosystem: docker
    directories:
      - /cmd/builder
      - /cmd/fetcher
      - /cmd/fission-bundle
      - /cmd/preupgradechecks
      - /cmd/reporter
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups: 
      docker-images:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update: semver-patch"]
        # Ignore dependencies in test directories
        paths:
          - "*/test/*"
          - "*/tests/*"
          - "*/*_test.go"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit:  5
    groups:
      go-dependencies:
        patterns: 
          - "*"
    ignore:
      - dependency-name:  "*"
        update-types:  ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
        # Ignore dependencies only used in test files
        paths:
          - "*/test/*"
          - "*/tests/*"
          - "*/*_test.go"
