sudo: required
dist: trusty
language: go

go:
- 1.8
- tip

cache:
  directories:
  - $HOME/google-cloud-sdk/
  - $HOME/k8scli

install:
- go get github.com/Masterminds/glide
- hack/travis-kube-setup.sh

env:
- KUBECONFIG=${HOME}/.kube/config PATH=$HOME/k8scli:${PATH}

script:
- cd ${TRAVIS_BUILD_DIR}
- glide install
- ./fission-bundle/build.sh
- hack/verify-gofmt.sh
- hack/runtests.sh
- test/build_and_test.sh
