sudo: required
dist: trusty
language: go

go:
- 1.8
- tip

cache:
  directories:
  - $HOME/google-cloud-sdk/

install:
- go get github.com/Masterminds/glide
- hack/travis-kube-setup.sh

env:
- KUBECONFIG=${HOME}/.kube/config

script:
- cd ${TRAVIS_BUILD_DIR}
- glide install
- ./fission-bundle/build.sh
- hack/verify-gofmt.sh
- go test -v -i $(go list ./... | grep -v '/vendor/' | grep -v 'examples/go')
- go test -v $(go list ./... | grep -v '/vendor/' | grep -v 'examples/go')

