{{- if .Values.canaryDeployment.enabled }}
{{- include "fission-role-generator" (merge (dict "namespace" .Values.defaultNamespace "component" "canaryconfig") .) }}

{{- if not .Values.fissionOnAllNamespaces -}}
  {{- if gt (len .Values.additionalFissionNamespaces) 0 }}
  {{- range $namespace := $.Values.additionalFissionNamespaces }}
  {{ include "fission-role-generator" (merge (dict "namespace" $namespace "component" "canaryconfig") $) }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
