{{/* 
Passing namespace as an argument to the "fissionFunction.rolebindings" template.
Need to use merge function to pass in the current scope so that ".Release" values
can be used
 */}}
{{ include "fissionFunction.rolebindings" (merge (dict "namespace" .Values.defaultNamespace) .) }}

{{- if not .Values.fissionOnAllNamespaces }}
  {{- if gt (len .Values.additionalFissionNamespaces) 0 }}
  {{- range $namespace := $.Values.additionalFissionNamespaces }}
  {{ include "fissionFunction.rolebindings" (merge (dict "namespace" $namespace) $) }}
  {{- end }}
  {{- end }}
{{- end }}
