{{/* 
Passing namespace as an argument to the "fissionFunction.rolebindings" template.
Need to use merge function to pass in the current scope so that ".Release" values
can be used
 */}}
{{ include "fissionFunction.rolebindings" (merge (dict "namespace" .Values.defaultNamespace) .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-fission-fetcher-pod-reader
  namespace: {{ .Values.defaultNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-event-fetcher
subjects:
  - kind: ServiceAccount
    name: fission-fetcher
    namespace: {{ .Values.defaultNamespace }}

{{- if not .Values.singleDefaultNamespace }}
{{- range $namespace := $.Values.additionalFissionNamespaces }}
{{ include "fissionFunction.rolebindings" (merge (dict "namespace" $namespace) $) }}
{{- end }}
{{- end }}
