apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-fission-fetcher
  namespace: {{ .Values.defaultNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - fission.io
    resources:
      - canaryconfigs
      - environments
      - functions
      - httptriggers
      - kuberneteswatchtriggers
      - messagequeuetriggers
      - packages
      - timetriggers
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-fission-builder
  namespace: {{ .Values.defaultNamespace }}
rules:
  - apiGroups:
      - fission.io
    resources:
      - canaryconfigs
      - environments
      - functions
      - httptriggers
      - kuberneteswatchtriggers
      - messagequeuetriggers
      - packages
      - timetriggers
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.functionNamespace }}
  name: event-fetcher
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["*"]
