apiVersion: v1
name: fission-core
version: 0.3.0-rc
description: Fission is a fast serverless framework for Kubernetes.
keywords:
- fission
- serverless
home: http://fission.io/
maintainers:
  - name: Soam Vasani
    email: soamvasani@platform9.com
  - name: Ta Ching Chen
    email: contact@tachingchen.com
engine: gotpl
appVersion: 0.3.0-rc
