apiVersion: v2
name: fission-core
version: 1.13.0
description: Fission is a fast serverless framework for Kubernetes.
keywords:
- fission
- serverless
home: https://fission.io/
maintainers:
  - name: Vishal Biyani
    email: vishal@infracloud.io
  - name: Sanket Sudake
    email: sanket@infracloud.io
engine: gotpl
appVersion: 1.13.0
type: application
dependencies:
  - name: prometheus
    version: 13.2.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled