{{- include "kubernetes-role-generator" (merge (dict "namespace" .Values.defaultNamespace "component" "buildermgr") .) }}

{{- if not .Values.fissionOnAllNamespaces -}}
  {{- if gt (len .Values.additionalFissionNamespaces) 0 }}
  {{- range $namespace := $.Values.additionalFissionNamespaces }}
  {{ include "kubernetes-role-generator" (merge (dict "namespace" $namespace "component" "buildermgr") $) }}
  {{- end }}
  {{- end }}
  {{- if .Values.builderNamespace -}}
  {{ include "kubernetes-role-generator" (merge (dict "namespace" .Values.builderNamespace "component" "buildermgr") $) }}
  {{- end }}
  {{- if .Values.functionNamespace -}}
  {{ include "kubernetes-role-generator" (merge (dict "namespace" .Values.functionNamespace "component" "buildermgr") $) }}
  {{- end }}
{{- end }}
