apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-preupgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
