{{- if .Values.analyticsNonHelmInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-{{ .Chart.Version }}-{{ randNumeric 3 }}
  labels:
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
spec:
  #ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "name" . }}
      annotations:
        {{- if .Values.enableIstio }}
        "sidecar.istio.io/inject": "false"
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
        {{- if .Values.imageTag }}
          image: {{ .Values.postInstallReportImage }}:{{ .Values.imageTag }}
        {{- else }}
          image: {{ .Values.postInstallReportImage }}
        {{- end }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: [ "/reporter" ]
          args: ["event", "-c", "fission-use", "-a", "yaml-post-install", "-l", "{{ .Chart.Name }}-{{ .Chart.Version }}"]
          env:
            - name: GA_TRACKING_ID
              value: "{{ .Values.gaTrackingID }}"
{{- end }}
