{{- if .Values.logger.fluentbit.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  username: {{ .Values.logger.fluentbit.influxdb.adminUser | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}