apiVersion: v2
name: fission-all
version: 1.22.0
appVersion: v1.22.0
description: Fission is a fast serverless framework for Kubernetes.
kubeVersion: ">=1.28.0-0"
home: https://fission.io/
icon: https://fission.io/images/fission-logo-white.svg
sources:
  - https://github.com/fission/fission
  - https://github.com/fission/keda-connectors
keywords:
  - fission
  - serverless
  - platform
  - faas
  - functions
  - Integration & Delivery
maintainers:
  - name: Vishal Biyani
    email: vishal@infracloud.io
  - name: Sanket Sudake
    email: sanket@infracloud.io
type: application
annotations:
  artifacthub.io/signKey: |
    fingerprint: 2EAE29FDF8A387050C82CD5ABBDD4FD6A1FFCBF6
    url: https://raw.githubusercontent.com/fission/fission-charts/main/public_key/pgp_keys.asc
