apiVersion: v2
name: fission-all
version: v1.18.0
appVersion: v1.18.0
description: Fission is a fast serverless framework for Kubernetes.
home: https://fission.io/
icon: https://fission.io/images/fission-logo-white.svg
sources:
  - https://github.com/fission/fission
  - https://github.com/fission/keda-connectors
keywords:
  - fission
  - serverless
  - platform
  - faas
  - functions
  - Integration & Delivery
maintainers:
  - name: Vishal Biyani
    email: vishal@infracloud.io
  - name: Sanket Sudake
    email: sanket@infracloud.io
engine: gotpl
type: application