{{- if or (.Values.controller.enabled) (.Values.influxdb.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    svc: controller
    application: fission-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
    targetPort: 8888
{{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.controllerPort }}
{{- end }}
  selector:
    svc: controller
{{- end -}}